### ISSUE TITLE
is this obd scanner is suitable for other vechile?

### ISSUE THREAD

**Issue by youxiaojie** [laszlodaniel/ChryslerScanner#1]
is this obd scanner is suitable for other vechile?

**Comment by laszlodaniel** [comment]
Older Chrysler, Dodge and Jeep vehicles are known for using CCD/SCI-bus for diagnostic communication. Interestingly John Deere tractors also used CCD-bus but other than that this scanner is useless for other modern vehicles.

**Comment by youxiaojie** [comment]
do you have editable version of protocal details? I hope to arrange and edit it for hacking battery project. or do you have edited battery-hacking version?

a bit of confusing on data,sub data, payload equivalent to register read/write, register number, and register value?
